In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Expanded_data_with_more_features.csv")

In [3]:

print("First 5 rows:")
df.head()

First 5 rows:

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,5 - 10,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,5 - 10,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75

In [4]:

print("\nLast 5 rows:")
df.tail()

Last 5 rows:

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
30636,816,female,group D,high school,standard,none,single,sometimes,no,2.0,school_bus,5 - 10,59,61,65
30637,890,male,group E,high school,standard,none,single,regularly,no,1.0,private,5 - 10,58,53,51
30638,911,female,NaN,high school,free/reduced,completed,married,sometimes,no,1.0,private,5 - 10,61,70,67
30639,934,female,group D,associate's degree,standard,completed,married,regularly,no,3.0,school_bus,5 - 10,82,90,93
30640,960,male,group B,some college,standard,none,married,never,no,1.0,school_bus,5 - 10,64,60,58

In [5]:

print("\nDataset Shape:", df.shape)
print("\nDataset Info:")
df.info()

Dataset Shape: (30641, 15)

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           30641 non-null  int64
 1   Gender               30641 non-null  str
 2   EthnicGroup          28801 non-null  str
 3   ParentEduc           28796 non-null  str
 4   LunchType            30641 non-null  str
 5   TestPrep             28811 non-null  str
 6   ParentMaritalStatus  29451 non-null  str
 7   PracticeSport        30010 non-null  str
 8   IsFirstChild         29737 non-null  str
 9   NrSiblings           29069 non-null  float64
 10  TransportMeans       27507 non-null  str
 11  WklyStudyHours       29686 non-null  str
 12  MathScore            30641 non-null  int64
 13  ReadingScore         30641 non-null  int64
 14  WritingScore         30641 non-null  int64
dtypes: float64(1), int64(4), str(10)
memory usage: 5.6 MB

In [6]:

print("\nDescriptive Statistics:")
print(df.describe())

Descriptive Statistics:
         Unnamed: 0    NrSiblings     MathScore  ReadingScore  WritingScore
count  30641.000000  29069.000000  30641.000000  30641.000000  30641.000000
mean     499.556607      2.145894     66.558402     69.377533     68.418622
std      288.747894      1.458242     15.361616     14.758952     15.443525
min        0.000000      0.000000      0.000000     10.000000      4.000000
25%      249.000000      1.000000     56.000000     59.000000     58.000000
50%      500.000000      2.000000     67.000000     70.000000     69.000000
75%      750.000000      3.000000     78.000000     80.000000     79.000000
max      999.000000      7.000000    100.000000    100.000000    100.000000

In [7]:

print("\nMissing Values Count:")
print(df.isnull().sum())

print("\nDuplicates Count:", df.duplicated().sum())

Missing Values Count:
Unnamed: 0                0
Gender                    0
EthnicGroup            1840
ParentEduc             1845
LunchType                 0
TestPrep               1830
ParentMaritalStatus    1190
PracticeSport           631
IsFirstChild            904
NrSiblings             1572
TransportMeans         3134
WklyStudyHours          955
MathScore                 0
ReadingScore              0
WritingScore              0
dtype: int64

Duplicates Count: 0

In [8]:
df.head()

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,5 - 10,69,90,88
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,5 - 10,45,56,42
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75

In [9]:
if 'Unnamed: 0' in df.columns:
    df.drop('Unnamed: 0', axis=1, inplace=True)

df['NrSiblings'] = df['NrSiblings'].fillna(df['NrSiblings'].median())

In [10]:

categorical_cols = ['EthnicGroup', 'ParentEduc', 'TestPrep', 'ParentMaritalStatus', 
                    'PracticeSport', 'IsFirstChild', 'TransportMeans', 'WklyStudyHours']

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# (Mapping/Encoding)
study_mapping = {'< 5': 1, '5 - 10': 2, '> 10': 3}
value_mapping = {'no': 0, 'yes': 1}
test_mapping = {'none': 0, 'completed': 1}

df['WklyStudyHours_Encoded'] = df['WklyStudyHours'].map(study_mapping)
df['IsFirstChild_Encoded'] = df['IsFirstChild'].map(value_mapping)
df['TestPrep_Encoded'] = df['TestPrep'].map(test_mapping)

In [11]:
print("\nعدد القيم المفقودة بعد التنظيف")
print(df.isnull().sum())

عدد القيم المفقودة بعد التنظيف
Gender                    0
EthnicGroup               0
ParentEduc                0
LunchType                 0
TestPrep                  0
ParentMaritalStatus       0
PracticeSport             0
IsFirstChild              0
NrSiblings                0
TransportMeans            0
WklyStudyHours            0
MathScore                 0
ReadingScore              0
WritingScore              0
WklyStudyHours_Encoded    0
IsFirstChild_Encoded      0
TestPrep_Encoded          0
dtype: int64

In [12]:
from IPython.display import display

print("\nUsing loc:")
display(df.loc[0:4, ['Gender', 'MathScore', 'ReadingScore']])

print("\nUsing iloc:")
display(df.iloc[0:5, 0:3])

Using loc:

   Gender  MathScore  ReadingScore
0  female         71            71
1  female         69            90
2  female         87            93
3    male         45            56
4    male         76            78

Using iloc:

   Gender EthnicGroup          ParentEduc
0  female     group C   bachelor's degree
1  female     group C        some college
2  female     group B     master's degree
3    male     group A  associate's degree
4    male     group C        some college

In [ ]:

# 2. (Multi-condition Filtering)
filtered_data = df[(df['MathScore'] > 80) & (df['TestPrep'] == 'completed')]
print("\nFiltered Data (MathScore > 80 AND TestPrep = completed):", len(filtered_data))

# 3. (Sorting)
sorted_data = df.sort_values(by='MathScore', ascending=False)
print("\nTop 5 Students in Math:")
print(sorted_data[['Gender', 'MathScore']].head())

# 4.  (GroupBy)
grouped_data = df.groupby('ParentEduc')[['MathScore', 'ReadingScore', 'WritingScore']].mean()
print("\nAverage Scores by Parent Education:")
print(grouped_data)

Filtered Data (MathScore > 80 AND TestPrep = completed): 2475

Top 5 Students in Math:
       Gender  MathScore
16243    male        100
20913  female        100
29124    male        100
10535    male        100
7771     male        100

Average Scores by Parent Education:
                    MathScore  ReadingScore  WritingScore
ParentEduc
associate's degree  68.365586     71.124324     70.299099
bachelor's degree   70.466627     73.062020     73.331069
high school         64.435731     67.213997     65.421136
master's degree     72.336134     75.832921     76.356896
some college        66.445978     69.189667     68.456711
some high school    62.584013     65.510785     63.632409

:

In [ ]:
plt.figure(figsize=(15, 12))

# Plot 1: Histogram / KDE (Math Score Distribution)
plt.subplot(3, 2, 1)
sns.histplot(df['MathScore'], kde=True, color='blue')
plt.title('1. Distribution of Math Scores')

# Plot 2: Boxplot (Math Score by Gender)
plt.subplot(3, 2, 2)
sns.boxplot(x='Gender', y='MathScore', data=df, hue='Gender', palette='Set2', legend=False)
plt.title('2. Math Scores by Gender')

# Plot 3: Bar Chart (Average Math Score by Parent Education)
plt.subplot(3, 2, 3)
sns.barplot(x='MathScore', y='ParentEduc', data=df, errorbar=None, hue='ParentEduc', palette='viridis', legend=False)
plt.title('3. Mean Math Score by Parent Education')

# Plot 4: Scatter Plot (Math Score vs Reading Score)
plt.subplot(3, 2, 4)
sns.scatterplot(x='MathScore', y='ReadingScore', hue='TestPrep', data=df, alpha=0.5)
plt.title('4. Math Score vs Reading Score')

# Plot 5: Correlation Heatmap
plt.subplot(3, 2, 5)
sns.heatmap(df[['MathScore', 'ReadingScore', 'WritingScore', 'NrSiblings']].corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('5. Correlation Matrix Heatmap')

plt.tight_layout()
plt.show()